In [41]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

In [52]:
from sklearn import datasets
dataset_iris=datasets.load_iris()
x=dataset_iris['data'].copy()
y=dataset_iris['target'].copy()

In [53]:
x

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [72]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=666)

In [51]:
train_x

array([[-0.76415145,  2.5457004 , -1.29021361, -1.46372368],
       [-1.47224546,  0.36712953, -1.34700951, -1.33005028],
       [ 1.00608357,  0.12506611,  1.03841844,  1.61076441],
       [-1.59026112, -1.81144133, -1.40380542, -1.19637689],
       [ 0.5340209 , -1.81144133,  0.35686759,  0.14035707],
       [-0.76415145,  1.09331982, -1.29021361, -1.33005028],
       [-0.05605744, -0.84318761,  0.18647988, -0.26066312],
       [-0.88216712,  0.60919296, -1.1766218 , -0.9290301 ],
       [-0.05605744, -0.60112418,  0.75443892,  1.61076441],
       [-1.00018278, -1.81144133, -0.26788734, -0.26066312],
       [-1.00018278,  1.09331982, -1.40380542, -1.19637689],
       [-0.17407311, -0.11699732,  0.24327579,  0.00668367],
       [-1.00018278,  0.85125639, -1.2334177 , -1.06270349],
       [-0.64613578,  1.57744668, -1.29021361, -1.33005028],
       [ 0.06195823,  0.36712953,  0.58405121,  0.80872404],
       [-0.17407311, -1.08525104, -0.15429554, -0.26066312],
       [-1.35422979,  0.

In [68]:
from sklearn.preprocessing import StandardScaler
knn_StandardScaler=StandardScaler()
knn_StandardScaler.fit(train_x)
train_x=knn_StandardScaler.transform(train_x)
test_x=knn_StandardScaler.transform(test_x)
knn_StandardScaler.mean_
knn_StandardScaler.scale_

array([ 1.,  1.,  1.,  1.])

## 网格搜索

In [45]:
param_grid=[
    {'n_neighbors':[k for k in range(1,11)],
    'weights':['uniform']},
    {'n_neighbors':[k for k in range(1,11)],
    'weights':['distance'],
    'p':[p for p in range(1,11)]}
]

In [46]:
from sklearn.neighbors import KNeighborsClassifier
knn_cls=KNeighborsClassifier()
from sklearn.model_selection import GridSearchCV
knn_GridSearchCV= GridSearchCV(knn_cls,param_grid,verbose=2)
knn_GridSearchCV.fit(train_x,train_y)

Fitting 3 folds for each of 110 candidates, totalling 330 fits
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=1, weights=uniform ..................................
[CV] ................... n_neighbors=1, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=2, weights=uniform ..................................
[CV] ................... n_neighbors=2, weights=uniform, total=   0.0s
[CV] n_neighbors=3, weights=uniform ..................................
[CV] .........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ............. n_neighbors=2, p=1, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=1, weights=distance ............................
[CV] ............. n_neighbors=2, p=1, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=2, weights=distance ............................
[CV] ............. n_neighbors=2, p=2, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=2, weights=distance ............................
[CV] ............. n_neighbors=2, p=2, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=2, weights=distance ............................
[CV] ............. n_neighbors=2, p=2, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=3, weights=distance ............................
[CV] ............. n_neighbors=2, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=3, weights=distance ............................
[CV] ............. n_neighbors=2, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=2, p=3, weights=distance ............................
[CV] .

[CV] n_neighbors=5, p=3, weights=distance ............................
[CV] ............. n_neighbors=5, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=3, weights=distance ............................
[CV] ............. n_neighbors=5, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=3, weights=distance ............................
[CV] ............. n_neighbors=5, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=4, weights=distance ............................
[CV] ............. n_neighbors=5, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=4, weights=distance ............................
[CV] ............. n_neighbors=5, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=4, weights=distance ............................
[CV] ............. n_neighbors=5, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=5, p=5, weights=distance ............................
[CV] ............. n_neighbors=5, p=5, weights=distance, total=   0.0s
[CV] n

[CV] n_neighbors=7, p=8, weights=distance ............................
[CV] ............. n_neighbors=7, p=8, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=8, weights=distance ............................
[CV] ............. n_neighbors=7, p=8, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=8, weights=distance ............................
[CV] ............. n_neighbors=7, p=8, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=9, weights=distance ............................
[CV] ............. n_neighbors=7, p=9, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=9, weights=distance ............................
[CV] ............. n_neighbors=7, p=9, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=9, weights=distance ............................
[CV] ............. n_neighbors=7, p=9, weights=distance, total=   0.0s
[CV] n_neighbors=7, p=10, weights=distance ...........................
[CV] ............ n_neighbors=7, p=10, weights=distance, total=   0.0s
[CV] n

[CV] ............ n_neighbors=10, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=3, weights=distance ...........................
[CV] ............ n_neighbors=10, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=3, weights=distance ...........................
[CV] ............ n_neighbors=10, p=3, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=4, weights=distance ...........................
[CV] ............ n_neighbors=10, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=4, weights=distance ...........................
[CV] ............ n_neighbors=10, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=4, weights=distance ...........................
[CV] ............ n_neighbors=10, p=4, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=5, weights=distance ...........................
[CV] ............ n_neighbors=10, p=5, weights=distance, total=   0.0s
[CV] n_neighbors=10, p=5, weights=distance ...........................
[CV] .

[Parallel(n_jobs=1)]: Done 330 out of 330 | elapsed:    1.5s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'weights': ['uniform']}, {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'weights': ['distance'], 'p': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=2)

In [47]:
knn_GridSearchCV.best_params_

{'n_neighbors': 6, 'p': 3, 'weights': 'distance'}

In [48]:
knn_cls=KNeighborsClassifier(n_neighbors=6,weights='distance',p=3)
knn_cls.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=3,
           weights='distance')

In [50]:
knn_cls.score(test_x,test_y)

0.93333333333333335

In [65]:
x_predict=np.array([4.4,  2.0 ,  3.4,  4.2])
x_predict_standard=knn_StandardScaler.transform(x_predict)
x_predict=x_predict.reshape(1,-1)
knn_cls.predict(x_predict)

D:\anaconda\lib\site-packages\sklearn\preprocessing\data.py:649: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


array([2])